# Place any default configuration for solr_wrapper here
# you must first run 'rake engine_cart:generate' to create the test app
# before running 'solr_wrapper' from project root
# port: 8983

# single-term autocomplete only works with Solr < 8
# requires adding tokenizing-suggest-v1.0.1.jar to Solr's contrib directory
# see README for details
# version: 7.7.3

version: 8.11.4
collection:
  dir: ./.internal_test_app/solr/conf/
  name: blacklight-core
