language: ruby
sudo: false
dist: focal

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - ENGINE_CART_RAILS_OPTIONS='--skip-git --skip-listen --skip-spring --skip-keeps --skip-action-cable --skip-coffee --skip-test'

matrix:
  include:
    - rvm: 3.1.6
      env: "RAILS_VERSION=6.1.7.8"
    - rvm: 3.0.6
      env: "RAILS_VERSION=6.1.7.4"
    - rvm: 2.7.8
      env: "RAILS_VERSION=6.0.6"
fast_finish: true

jdk: openjdk17
