language: ruby
sudo: false
dist: focal

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &
  - gem update --system --no-document
  - gem install bundler:2.5.19 --no-document

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - ENGINE_CART_RAILS_OPTIONS='--skip-git --skip-listen --skip-spring --skip-keeps --skip-action-cable --skip-coffee --skip-test'

matrix:
  include:
    - rvm: 3.2.5
      env: "RAILS_VERSION=7.2.1.2"
    - rvm: 3.1.6
      env: "RAILS_VERSION=7.0.8.4"
    - rvm: 3.0.6
      env: "RAILS_VERSION=6.1.7.8"
fast_finish: true

jdk: openjdk11
