# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: test (ruby ${{ matrix.ruby }} / rails ${{ matrix.rails_version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.1"]
        rails_version: ["7.0.8.4"]
        include:
          - ruby-version: "3.0"
            rails_version: "6.1.7.8"
    env:
      ENGINE_CART_RAILS_OPTIONS: "--skip-git --skip-listen --skip-spring --skip-keeps --skip-coffee --skip-test"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler: "latest"
      - name: Install dependencies
        run: bundle install
      - name: Run linter and tests
        run: bundle exec rake ci
